// <auto-generated />
using System;
using EShopProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShopProject.EShopDB.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    [Migration("20251021124345_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShopProject.Business.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("Idate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Udate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance gaming laptop with RTX 4070, 32GB RAM, and 1TB SSD",
                            Idate = new DateTime(2025, 9, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302",
                            Name = "Gaming Laptop Pro X15",
                            Price = 34999.99m,
                            Quantity = 15,
                            Udate = new DateTime(2025, 9, 21, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Premium noise-cancelling headphones with 30-hour battery life",
                            Idate = new DateTime(2025, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
                            Name = "Wireless Bluetooth Headphones",
                            Price = 2499.00m,
                            Quantity = 45,
                            Udate = new DateTime(2025, 9, 26, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Professional 4K monitor with HDR support and 144Hz refresh rate",
                            Idate = new DateTime(2025, 10, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
                            Name = "4K Ultra HD Monitor 32\"",
                            Price = 12999.00m,
                            Quantity = 8,
                            Udate = new DateTime(2025, 10, 1, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Description = "RGB mechanical keyboard with Cherry MX switches",
                            Idate = new DateTime(2025, 10, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
                            Name = "Mechanical Gaming Keyboard RGB",
                            Price = 3299.00m,
                            Quantity = 32,
                            Udate = new DateTime(2025, 10, 6, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Latest flagship smartphone with advanced camera system",
                            Idate = new DateTime(2025, 10, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9",
                            Name = "Smartphone Pro Max 256GB",
                            Price = 28999.00m,
                            Quantity = 22,
                            Udate = new DateTime(2025, 10, 11, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
